# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-toml
      - id: check-merge-conflict
      - id: check-yaml
        args: [ '--unsafe' ]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.9.0  # Black version
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # isort version
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/python-poetry/poetry
    rev: 1.6.1  # Poetry version
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.285  # Ruff version
    hooks:
      - id: ruff
